# Generated by Django 4.1.5 on 2023-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="maquillaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("nombre", models.CharField(max_length=15, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(max_length=255, verbose_name="descripcion"),
                ),
                ("img", models.ImageField(upload_to="", verbose_name="imagen")),
            ],
        ),
    ]
