# Generated by Django 4.1.5 on 2023-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquillajes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquillaje",
            name="img",
            field=models.ImageField(
                upload_to="C:/Users/Usuario/Desktop/cursos/django/sabela/static/img",
                verbose_name="imagen",
            ),
        ),
    ]
