# Generated by Django 4.1.5 on 2023-02-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquillajes", "0003_alter_maquillaje_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquillaje",
            name="tipo",
            field=models.CharField(max_length=50, null=True, verbose_name="tipo"),
        ),
    ]
