# Generated by Django 4.1.5 on 2023-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquillajes", "0004_maquillaje_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquillaje",
            name="nombre",
            field=models.CharField(max_length=43, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="maquillaje",
            name="tipo",
            field=models.CharField(max_length=50, verbose_name="tipo"),
        ),
    ]
